general.import = [ "~/.config/theme/current/alacritty.toml" ]

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
bold = { family = "JetBrainsMonoNerdFont", style = "Bold" }
italic = { family = "JetBrainsMonoNerdFont", style = "italic" }
bold_italic = { family = "JetBrainsMonoNerdFont", style = "Bold Italic" }

size = 14

[window]
opacity = 0.96
padding = {x=15, y=15}
decorations = "None"

[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"
