#!/bin/bash

if [ $# -ne 3 ]; then
    echo "Usage: $0 <cpp_a> <cpp_b> <cpp_generator>"
    exit 1
fi

cpp_a="./$1.cpp"
cpp_b="./$2.cpp"
cpp_gen="./$3.cpp"

exe_a="/tmp/$1.exe"
exe_b="/tmp/$2.exe"
exe_gen="/tmp/$3.exe"

input="/tmp/tmpin"
out_a="/tmp/tmpouta"
out_b="/tmp/tmpoutb"

diff_input="./diffin"

trap 'rm "$input" "$out_a" "$out_b" "$exe_a" "$exe_b" "$exe_gen"' EXIT

g++ -O2 -Wall -Wextra -Wshadow -Wno-sign-compare -fdiagnostics-color=always -o "$exe_a" "$cpp_a"
if [ $? -ne 0 ]; then
    echo -e "\e[31mA file compilation failed!\e[0m"
    exit 1
fi
g++ -O2 -Wall -Wextra -Wshadow -Wno-sign-compare -fdiagnostics-color=always -o "$exe_b" "$cpp_b"
if [ $? -ne 0 ]; then
    echo -e "\e[31mB file compilation failed!\e[0m"
    exit 1
fi
g++ -O2 -Wall -Wextra -Wshadow -Wno-sign-compare -fdiagnostics-color=always -o "$exe_gen" "$cpp_gen"
if [ $? -ne 0 ]; then
    echo -e "\e[31mGenerator compilation failed!\e[0m"
    exit 1
fi

idx=1
next_info=1

while true; do
    "$exe_gen" > "$input"
    "$exe_a" < "$input" > "$out_a"
    "$exe_b" < "$input" > "$out_b"
    diff -w --color=always -u "$out_a" "$out_b"
    if [ $? -ne 0 ]; then
        cp "$input" "$diff_input"
        cat "$diff_input"
        echo -e "\e[31mTEST $idx FAILED\e[0m"
        exit 0
    else
        if [ $idx -eq $next_info ]; then
            echo -e "\e[32mTEST $idx PASSED\e[0m"
            ((next_info=next_info*2))
        fi
    fi
    ((idx++))
done
